import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-10 sm:mt-0">
        <div>
          <h5>Basit para izcisi</h5>
          <p>
            Günlük işlemleri kaydetmek saniyeler sürer. Bunları Gider: Yiyecek,
            Alışveriş veya Gelir: Maaş, Hediye gibi net ve görselleştirilmiş
            kategorilere ayırın.
          </p>
          <p>Kusursuz Bütçeleme</p>
          <p>
            Kendi harcama alışkanlıklarınıza göre, uyması kolay bütçeler
            belirleyin. Satın almak istediğiniz şeye bir adım daha yakınsınız.
          </p>
          <p>Mali dengeniz tek ekranda</p>{" "}
          <p>
            Harcama kalıplarınız hakkında net bir görüş sağlayan bir rapor.
            Okunması kolay grafiklerle paranızın nereden gelip gittiğini
            anlayın.{" "}
          </p>
        </div>
      </div>
    </div>
  );
}
